#A configMap is holder of environment variable which can be injected to any of the kubernets resources
# Usually values that are common  accross the applicaton will be placed in a configMap and will be used inside the pods
# To use configMap , we would use envFROM
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecomm-configmap
data:
  MONGODB_URL: "mongodb.roboshop.internal"
  ENV: dev
  BATCH: "54"
  APP: ecomm
  DEV: mikel

---

apiVersion: v1
kind: Pod
metadata:
  name: centos-with-cm
spec:
  containers: 
  - name: centos
    image: centos:7
    command: ["sleep" , "1000"]
    envFrom:
      - configMapRef:
          name: ecomm-configmap  

