# Probes in kubernetes are typically healthchecks
# Health checks are of 3 types in kubernetes

#1)Liveless probles:
#2_ Readiness probes;
#3)startup probes;

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec-pod
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5